apiVersion: v1 
kind: Service 
metadata: 
  name: nginx-service 
spec: 
  selector:      
    app: nginx-glusterfs
  type: NodePort
  ports: 
  - name: http 
    protocol: TCP
    port: 80      
    targetPort: 80 
---
apiVersion: apps/v1beta2
kind: Deployment
metadata: 
  name: glusterfs-deployment
  namespace: default
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: nginx-glusterfs
  template: 
    metadata:
      labels:
        app: nginx-glusterfs
    spec:
      containers: 
      - name: nginx-glusterfs
        image: nginx:1.13
        volumeMounts:
        - name: html-glusterfs
          mountPath: /usr/share/nginx/html 
        ports: 
        - containerPort: 80
      volumes:
      - name: html-glusterfs
        persistentVolumeClaim:
          claimName: glusterfs-pvc001
