apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    name: glusterfs-pv001
  name: glusterfs-pv001
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  glusterfs:
    endpoints: glusterfs-cluster
    path: gv0
  persistentVolumeReclaimPolicy: Recycle
