apiVersion: v1
kind: Pod 
metadata: 
  name: pod-vol-nfs
  namespace: default
spec: 
  containers: 
  - name: nginx-test1 
    image: nginx:1.13
    volumeMounts:
    - name: html 
      mountPath: /usr/share/nginx/html 
  volumes:
  - name: html 
    nfs:
      path: /data/vol
      server: nfs.wangfang.com
