apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-basic
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: www.nginx.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 88