apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: kube-system
spec:
  selector: 
    app: prometheus
  type: NodePort
  ports:
    - port: 8080
      targetPort: 9090 
      nodePort: 30013
